title: Yingshuo Li's Homepage
page-top-title: Yingshuo Li
top-section-bg-text: Art and Technology
home-subtitle: Yingshuo Li&ensp;|&ensp;李英硕
copyright-text: '&copy; Yingshuo Li 2024. All Rights Reserved.'
